---
apiVersion: v1
kind: Service
metadata:
  name: interview
spec:
  selector:
    app.kubernetes.io/name: interview
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interview
  labels:
    app: interview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interview
  template:
    metadata:
      name: interview
      labels:
        app: interview
    spec:
      containers:
      - name: interview
        image: localhost:5000/platform-interview:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: interview
spec:
  ingressClassName: "traefik"
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: interview
            port:
              number: 8080
